# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/zhuyushuang/python_practice/2048.ui',
# licensing of '/Users/zhuyushuang/python_practice/2048.ui' applies.
#
# Created: Tue Mar 24 17:36:29 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(514, 496)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(2, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.p7 = QtWidgets.QPushButton(self.centralwidget)
        self.p7.setMinimumSize(QtCore.QSize(70, 70))
        self.p7.setText("")
        self.p7.setObjectName("p7")
        self.pbtn_img = QtWidgets.QButtonGroup(MainWindow)
        self.pbtn_img.setObjectName("pbtn_img")
        self.pbtn_img.addButton(self.p7)
        self.gridLayout_2.addWidget(self.p7, 1, 2, 1, 1)
        self.p10 = QtWidgets.QPushButton(self.centralwidget)
        self.p10.setMinimumSize(QtCore.QSize(70, 70))
        self.p10.setText("")
        self.p10.setObjectName("p10")
        self.pbtn_img.addButton(self.p10)
        self.gridLayout_2.addWidget(self.p10, 2, 1, 1, 1)
        self.p6 = QtWidgets.QPushButton(self.centralwidget)
        self.p6.setMinimumSize(QtCore.QSize(70, 70))
        self.p6.setText("")
        self.p6.setObjectName("p6")
        self.pbtn_img.addButton(self.p6)
        self.gridLayout_2.addWidget(self.p6, 1, 1, 1, 1)
        self.p8 = QtWidgets.QPushButton(self.centralwidget)
        self.p8.setMinimumSize(QtCore.QSize(70, 70))
        self.p8.setText("")
        self.p8.setObjectName("p8")
        self.pbtn_img.addButton(self.p8)
        self.gridLayout_2.addWidget(self.p8, 1, 3, 1, 1)
        self.p2 = QtWidgets.QPushButton(self.centralwidget)
        self.p2.setMinimumSize(QtCore.QSize(70, 70))
        self.p2.setText("")
        self.p2.setObjectName("p2")
        self.pbtn_img.addButton(self.p2)
        self.gridLayout_2.addWidget(self.p2, 0, 1, 1, 1)
        self.p12 = QtWidgets.QPushButton(self.centralwidget)
        self.p12.setMinimumSize(QtCore.QSize(70, 70))
        self.p12.setText("")
        self.p12.setObjectName("p12")
        self.pbtn_img.addButton(self.p12)
        self.gridLayout_2.addWidget(self.p12, 2, 3, 1, 1)
        self.p3 = QtWidgets.QPushButton(self.centralwidget)
        self.p3.setMinimumSize(QtCore.QSize(70, 70))
        self.p3.setText("")
        self.p3.setObjectName("p3")
        self.pbtn_img.addButton(self.p3)
        self.gridLayout_2.addWidget(self.p3, 0, 2, 1, 1)
        self.p9 = QtWidgets.QPushButton(self.centralwidget)
        self.p9.setMinimumSize(QtCore.QSize(70, 70))
        self.p9.setText("")
        self.p9.setObjectName("p9")
        self.pbtn_img.addButton(self.p9)
        self.gridLayout_2.addWidget(self.p9, 2, 0, 1, 1)
        self.p11 = QtWidgets.QPushButton(self.centralwidget)
        self.p11.setMinimumSize(QtCore.QSize(70, 70))
        self.p11.setText("")
        self.p11.setObjectName("p11")
        self.pbtn_img.addButton(self.p11)
        self.gridLayout_2.addWidget(self.p11, 2, 2, 1, 1)
        self.p1 = QtWidgets.QPushButton(self.centralwidget)
        self.p1.setMinimumSize(QtCore.QSize(70, 70))
        self.p1.setText("")
        self.p1.setObjectName("p1")
        self.pbtn_img.addButton(self.p1)
        self.gridLayout_2.addWidget(self.p1, 0, 0, 1, 1)
        self.p4 = QtWidgets.QPushButton(self.centralwidget)
        self.p4.setMinimumSize(QtCore.QSize(70, 70))
        self.p4.setText("")
        self.p4.setObjectName("p4")
        self.pbtn_img.addButton(self.p4)
        self.gridLayout_2.addWidget(self.p4, 0, 3, 1, 1)
        self.p5 = QtWidgets.QPushButton(self.centralwidget)
        self.p5.setMinimumSize(QtCore.QSize(70, 70))
        self.p5.setText("")
        self.p5.setObjectName("p5")
        self.pbtn_img.addButton(self.p5)
        self.gridLayout_2.addWidget(self.p5, 1, 0, 1, 1)
        self.p13 = QtWidgets.QPushButton(self.centralwidget)
        self.p13.setMinimumSize(QtCore.QSize(70, 70))
        self.p13.setText("")
        self.p13.setObjectName("p13")
        self.pbtn_img.addButton(self.p13)
        self.gridLayout_2.addWidget(self.p13, 3, 0, 1, 1)
        self.p14 = QtWidgets.QPushButton(self.centralwidget)
        self.p14.setMinimumSize(QtCore.QSize(70, 70))
        self.p14.setText("")
        self.p14.setObjectName("p14")
        self.pbtn_img.addButton(self.p14)
        self.gridLayout_2.addWidget(self.p14, 3, 1, 1, 1)
        self.p15 = QtWidgets.QPushButton(self.centralwidget)
        self.p15.setMinimumSize(QtCore.QSize(70, 70))
        self.p15.setText("")
        self.p15.setObjectName("p15")
        self.pbtn_img.addButton(self.p15)
        self.gridLayout_2.addWidget(self.p15, 3, 2, 1, 1)
        self.p16 = QtWidgets.QPushButton(self.centralwidget)
        self.p16.setMinimumSize(QtCore.QSize(70, 70))
        self.p16.setText("")
        self.p16.setObjectName("p16")
        self.pbtn_img.addButton(self.p16)
        self.gridLayout_2.addWidget(self.p16, 3, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.left = QtWidgets.QPushButton(self.centralwidget)
        self.left.setMinimumSize(QtCore.QSize(70, 50))
        self.left.setObjectName("left")
        self.gridLayout_3.addWidget(self.left, 1, 0, 1, 1)
        self.right = QtWidgets.QPushButton(self.centralwidget)
        self.right.setMinimumSize(QtCore.QSize(70, 50))
        self.right.setObjectName("right")
        self.gridLayout_3.addWidget(self.right, 1, 2, 1, 1)
        self.down = QtWidgets.QPushButton(self.centralwidget)
        self.down.setMinimumSize(QtCore.QSize(70, 50))
        self.down.setObjectName("down")
        self.gridLayout_3.addWidget(self.down, 2, 1, 1, 1)
        self.up = QtWidgets.QPushButton(self.centralwidget)
        self.up.setMinimumSize(QtCore.QSize(70, 50))
        self.up.setObjectName("up")
        self.gridLayout_3.addWidget(self.up, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.restart = QtWidgets.QPushButton(self.centralwidget)
        self.restart.setMinimumSize(QtCore.QSize(250, 50))
        self.restart.setObjectName("restart")
        self.gridLayout_4.addWidget(self.restart, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.left.setText(QtWidgets.QApplication.translate("MainWindow", "left", None, -1))
        self.right.setText(QtWidgets.QApplication.translate("MainWindow", "right", None, -1))
        self.down.setText(QtWidgets.QApplication.translate("MainWindow", "down", None, -1))
        self.up.setText(QtWidgets.QApplication.translate("MainWindow", "up", None, -1))
        self.restart.setText(QtWidgets.QApplication.translate("MainWindow", "restart", None, -1))

